'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace TekServiceRef
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://microsoft.com/webservices/", ConfigurationName:="TekServiceRef.TEkServiceSoap")>  _
    Public Interface TEkServiceSoap
        
        'CODEGEN: Контракт генерации сообщений с именем Qry из пространства имен http://microsoft.com/webservices/ не отмечен как обнуляемый
        <System.ServiceModel.OperationContractAttribute(Action:="http://microsoft.com/webservices/MeasurementsGet", ReplyAction:="*")>  _
        Function MeasurementsGet(ByVal request As TekServiceRef.MeasurementsGetRequest) As TekServiceRef.MeasurementsGetResponse
        
        'CODEGEN: Контракт генерации сообщений с именем Qry из пространства имен http://microsoft.com/webservices/ не отмечен как обнуляемый
        <System.ServiceModel.OperationContractAttribute(Action:="http://microsoft.com/webservices/NSGet", ReplyAction:="*")>  _
        Function NSGet(ByVal request As TekServiceRef.NSGetRequest) As TekServiceRef.NSGetResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class MeasurementsGetRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="MeasurementsGet", [Namespace]:="http://microsoft.com/webservices/", Order:=0)>  _
        Public Body As TekServiceRef.MeasurementsGetRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TekServiceRef.MeasurementsGetRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://microsoft.com/webservices/")>  _
    Partial Public Class MeasurementsGetRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Qry As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Qry As String)
            MyBase.New
            Me.Qry = Qry
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class MeasurementsGetResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="MeasurementsGetResponse", [Namespace]:="http://microsoft.com/webservices/", Order:=0)>  _
        Public Body As TekServiceRef.MeasurementsGetResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TekServiceRef.MeasurementsGetResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://microsoft.com/webservices/")>  _
    Partial Public Class MeasurementsGetResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MeasurementsGetResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MeasurementsGetResult As String)
            MyBase.New
            Me.MeasurementsGetResult = MeasurementsGetResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class NSGetRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="NSGet", [Namespace]:="http://microsoft.com/webservices/", Order:=0)>  _
        Public Body As TekServiceRef.NSGetRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TekServiceRef.NSGetRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://microsoft.com/webservices/")>  _
    Partial Public Class NSGetRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Qry As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Qry As String)
            MyBase.New
            Me.Qry = Qry
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class NSGetResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="NSGetResponse", [Namespace]:="http://microsoft.com/webservices/", Order:=0)>  _
        Public Body As TekServiceRef.NSGetResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As TekServiceRef.NSGetResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://microsoft.com/webservices/")>  _
    Partial Public Class NSGetResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public NSGetResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal NSGetResult As String)
            MyBase.New
            Me.NSGetResult = NSGetResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface TEkServiceSoapChannel
        Inherits TekServiceRef.TEkServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TEkServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of TekServiceRef.TEkServiceSoap)
        Implements TekServiceRef.TEkServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TekServiceRef_TEkServiceSoap_MeasurementsGet(ByVal request As TekServiceRef.MeasurementsGetRequest) As TekServiceRef.MeasurementsGetResponse Implements TekServiceRef.TEkServiceSoap.MeasurementsGet
            Return MyBase.Channel.MeasurementsGet(request)
        End Function
        
        Public Function MeasurementsGet(ByVal Qry As String) As String
            Dim inValue As TekServiceRef.MeasurementsGetRequest = New TekServiceRef.MeasurementsGetRequest()
            inValue.Body = New TekServiceRef.MeasurementsGetRequestBody()
            inValue.Body.Qry = Qry
            Dim retVal As TekServiceRef.MeasurementsGetResponse = CType(Me,TekServiceRef.TEkServiceSoap).MeasurementsGet(inValue)
            Return retVal.Body.MeasurementsGetResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TekServiceRef_TEkServiceSoap_NSGet(ByVal request As TekServiceRef.NSGetRequest) As TekServiceRef.NSGetResponse Implements TekServiceRef.TEkServiceSoap.NSGet
            Return MyBase.Channel.NSGet(request)
        End Function
        
        Public Function NSGet(ByVal Qry As String) As String
            Dim inValue As TekServiceRef.NSGetRequest = New TekServiceRef.NSGetRequest()
            inValue.Body = New TekServiceRef.NSGetRequestBody()
            inValue.Body.Qry = Qry
            Dim retVal As TekServiceRef.NSGetResponse = CType(Me,TekServiceRef.TEkServiceSoap).NSGet(inValue)
            Return retVal.Body.NSGetResult
        End Function
    End Class
End Namespace
