'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
<<<<<<< HEAD:TGKSender2/Backup/My Project/Application.Designer.vb
'     Runtime Version:4.0.30319.235
=======
'     Runtime Version:4.0.30319.261
>>>>>>> 1df6630c1f273a55783ddc7b5354cf723c2a001a:NCAnalizer/My Project/Application.Designer.vb
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

