version: '{branch}-{build}'
os: Visual Studio 2015
platform: Any CPU
shallow_clone: true
init:
- git config --global core.autocrlf true
before_build:
- nuget restore
build:
  verbosity: minimal
cache:
- packages -> **\packages.config
