'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
'
Namespace WebReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="IntegrationBinding", [Namespace]:="http://87.226.159.184/web-service/index/run/name/integration/")>  _
    Partial Public Class Integration
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getOperationCompleted As System.Threading.SendOrPostCallback
        
        Private postOperationCompleted As System.Threading.SendOrPostCallback
        
        Private putOperationCompleted As System.Threading.SendOrPostCallback
        
        Private deleteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ROSTELECOMINTEGRATION.My.MySettings.Default.ROSTELECOMINTEGRATION_WebReference_Integration
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getCompleted As getCompletedEventHandler
        
        '''<remarks/>
        Public Event postCompleted As postCompletedEventHandler
        
        '''<remarks/>
        Public Event putCompleted As putCompletedEventHandler
        
        '''<remarks/>
        Public Event deleteCompleted As deleteCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://87.226.159.184/web-service/index/run/name/integration/#get", RequestNamespace:="http://87.226.159.184/web-service/index/run/name/integration/", ResponseNamespace:="http://87.226.159.184/web-service/index/run/name/integration/", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function [get](ByVal request As RequestType) As <System.Xml.Serialization.XmlElementAttribute("return")> ResponseType
            Dim results() As Object = Me.Invoke("get", New Object() {request})
            Return CType(results(0),ResponseType)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getAsync(ByVal request As RequestType)
            Me.getAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getAsync(ByVal request As RequestType, ByVal userState As Object)
            If (Me.getOperationCompleted Is Nothing) Then
                Me.getOperationCompleted = AddressOf Me.OngetOperationCompleted
            End If
            Me.InvokeAsync("get", New Object() {request}, Me.getOperationCompleted, userState)
        End Sub
        
        Private Sub OngetOperationCompleted(ByVal arg As Object)
            If (Not (Me.getCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getCompleted(Me, New getCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://87.226.159.184/web-service/index/run/name/integration/#post", RequestNamespace:="http://87.226.159.184/web-service/index/run/name/integration/", ResponseNamespace:="http://87.226.159.184/web-service/index/run/name/integration/", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function post(ByVal request As RequestType) As <System.Xml.Serialization.XmlElementAttribute("return")> ResponseType
            Dim results() As Object = Me.Invoke("post", New Object() {request})
            Return CType(results(0),ResponseType)
        End Function
        
        '''<remarks/>
        Public Overloads Sub postAsync(ByVal request As RequestType)
            Me.postAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub postAsync(ByVal request As RequestType, ByVal userState As Object)
            If (Me.postOperationCompleted Is Nothing) Then
                Me.postOperationCompleted = AddressOf Me.OnpostOperationCompleted
            End If
            Me.InvokeAsync("post", New Object() {request}, Me.postOperationCompleted, userState)
        End Sub
        
        Private Sub OnpostOperationCompleted(ByVal arg As Object)
            If (Not (Me.postCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent postCompleted(Me, New postCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://87.226.159.184/web-service/index/run/name/integration/#put", RequestNamespace:="http://87.226.159.184/web-service/index/run/name/integration/", ResponseNamespace:="http://87.226.159.184/web-service/index/run/name/integration/", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function put(ByVal request As RequestType) As <System.Xml.Serialization.XmlElementAttribute("return")> ResponseType
            Dim results() As Object = Me.Invoke("put", New Object() {request})
            Return CType(results(0),ResponseType)
        End Function
        
        '''<remarks/>
        Public Overloads Sub putAsync(ByVal request As RequestType)
            Me.putAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub putAsync(ByVal request As RequestType, ByVal userState As Object)
            If (Me.putOperationCompleted Is Nothing) Then
                Me.putOperationCompleted = AddressOf Me.OnputOperationCompleted
            End If
            Me.InvokeAsync("put", New Object() {request}, Me.putOperationCompleted, userState)
        End Sub
        
        Private Sub OnputOperationCompleted(ByVal arg As Object)
            If (Not (Me.putCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent putCompleted(Me, New putCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://87.226.159.184/web-service/index/run/name/integration/#delete", RequestNamespace:="http://87.226.159.184/web-service/index/run/name/integration/", ResponseNamespace:="http://87.226.159.184/web-service/index/run/name/integration/", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function delete(ByVal request As RequestType) As <System.Xml.Serialization.XmlElementAttribute("return")> ResponseType
            Dim results() As Object = Me.Invoke("delete", New Object() {request})
            Return CType(results(0),ResponseType)
        End Function
        
        '''<remarks/>
        Public Overloads Sub deleteAsync(ByVal request As RequestType)
            Me.deleteAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub deleteAsync(ByVal request As RequestType, ByVal userState As Object)
            If (Me.deleteOperationCompleted Is Nothing) Then
                Me.deleteOperationCompleted = AddressOf Me.OndeleteOperationCompleted
            End If
            Me.InvokeAsync("delete", New Object() {request}, Me.deleteOperationCompleted, userState)
        End Sub
        
        Private Sub OndeleteOperationCompleted(ByVal arg As Object)
            If (Not (Me.deleteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent deleteCompleted(Me, New deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://87.226.159.184/web-service/index/run/name/integration/")>  _
    Partial Public Class RequestType
        
        Private headerField As HeaderType
        
        Private dataField() As Byte
        
        Private parametersField As ParametersType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Header() As HeaderType
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Data() As Byte()
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Parameters() As ParametersType
            Get
                Return Me.parametersField
            End Get
            Set
                Me.parametersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://87.226.159.184/web-service/index/run/name/integration/")>  _
    Partial Public Class HeaderType
        
        Private versionField As String
        
        Private operationField As String
        
        Private requestIdField As String
        
        Private sendDateField As Date
        
        Private senderField As String
        
        Private signatureField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Operation() As String
            Get
                Return Me.operationField
            End Get
            Set
                Me.operationField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property RequestId() As String
            Get
                Return Me.requestIdField
            End Get
            Set
                Me.requestIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SendDate() As Date
            Get
                Return Me.sendDateField
            End Get
            Set
                Me.sendDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sender() As String
            Get
                Return Me.senderField
            End Get
            Set
                Me.senderField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Signature() As String
            Get
                Return Me.signatureField
            End Get
            Set
                Me.signatureField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://87.226.159.184/web-service/index/run/name/integration/")>  _
    Partial Public Class ResponseType
        
        Private headerField As HeaderType
        
        Private codeField As String
        
        Private descriptionField As String
        
        Private dataField() As Byte
        
        Private parametersField As ParametersType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Header() As HeaderType
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Data() As Byte()
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Parameters() As ParametersType
            Get
                Return Me.parametersField
            End Get
            Set
                Me.parametersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://87.226.159.184/web-service/index/run/name/integration/")>  _
    Partial Public Class ParametersType
        
        Private parameterField() As ParameterType
        
        Private customParametersField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Parameter", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Parameter() As ParameterType()
            Get
                Return Me.parameterField
            End Get
            Set
                Me.parameterField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property CustomParameters() As Byte()
            Get
                Return Me.customParametersField
            End Get
            Set
                Me.customParametersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://87.226.159.184/web-service/index/run/name/integration/")>  _
    Partial Public Class ParameterType
        
        Private nameField As String
        
        Private valueField As Object
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Value() As Object
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub getCompletedEventHandler(ByVal sender As Object, ByVal e As getCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResponseType
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResponseType)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub postCompletedEventHandler(ByVal sender As Object, ByVal e As postCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class postCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResponseType
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResponseType)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub putCompletedEventHandler(ByVal sender As Object, ByVal e As putCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class putCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResponseType
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResponseType)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub deleteCompletedEventHandler(ByVal sender As Object, ByVal e As deleteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class deleteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResponseType
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResponseType)
            End Get
        End Property
    End Class
End Namespace
