CREATE TABLE "COUNTERS"."WEBREQEST" 
   (	"WEBREQESTID" NUMBER(18,0) NOT NULL ENABLE, 
	"ID_BD" NUMBER(5,0) NOT NULL ENABLE, 
	"PROCESSED" NUMBER(1,0) DEFAULT 0, 
	"CCURR" VARCHAR2(1) DEFAULT '0', 
	"CHOUR" VARCHAR2(1) DEFAULT '0', 
	"C24" VARCHAR2(1) DEFAULT '0', 
	"CSUM" VARCHAR2(1) DEFAULT '0', 
	"DFROMHOUR" DATE, 
	"DFROM24" DATE, 
	"DTOHOUR" DATE, 
	"DTO24" DATE, 
	 CONSTRAINT "WEBREQUEST_PK" PRIMARY KEY ("WEBREQESTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "WEBREQEST_BDEV" FOREIGN KEY ("ID_BD")
	  REFERENCES "COUNTERS"."BDEVICES" ("ID_BD") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "COUNTERS"."WEBREQUEST_PK" ON "COUNTERS"."WEBREQEST" ("WEBREQESTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER TABLE "COUNTERS"."WEBREQEST" ADD CONSTRAINT "WEBREQUEST_PK" PRIMARY KEY ("WEBREQESTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "COUNTERS"."WEBREQEST" MODIFY ("ID_BD" NOT NULL ENABLE);
  ALTER TABLE "COUNTERS"."WEBREQEST" MODIFY ("WEBREQESTID" NOT NULL ENABLE);
   COMMENT ON COLUMN "COUNTERS"."WEBREQEST"."ID_BD" IS '->BDEVICES';
   COMMENT ON COLUMN "COUNTERS"."WEBREQEST"."PROCESSED" IS '0 - в очереди  1 - идет опрос 2 - отработан';
   COMMENT ON COLUMN "COUNTERS"."WEBREQEST"."CCURR" IS '1 - опрашивать текущие';
   COMMENT ON COLUMN "COUNTERS"."WEBREQEST"."CHOUR" IS '1 - опрашивать часовые';
   COMMENT ON COLUMN "COUNTERS"."WEBREQEST"."C24" IS '1 - опрашивать суточные';
   COMMENT ON COLUMN "COUNTERS"."WEBREQEST"."CSUM" IS '1 - опрашивать итоговые';
   COMMENT ON COLUMN "COUNTERS"."WEBREQEST"."DFROMHOUR" IS 'Дата начала опроса часовых';
   COMMENT ON COLUMN "COUNTERS"."WEBREQEST"."DFROM24" IS 'Дата начала опроса  суточных';
   COMMENT ON COLUMN "COUNTERS"."WEBREQEST"."DTOHOUR" IS 'Дата завершения опроса часовых';
   COMMENT ON COLUMN "COUNTERS"."WEBREQEST"."DTO24" IS 'Дата завершения опроса суточных';
   COMMENT ON TABLE "COUNTERS"."WEBREQEST"  IS 'Запрос на опрос устройств';
   
   
   CREATE SEQUENCE  "COUNTERS"."WEBREQUEST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;